# Generated by Django 3.1 on 2022-02-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_types',
            field=models.IntegerField(blank=True, choices=[(1, 'Like'), (2, 'Comment'), (3, 'Follow')], null=True),
        ),
    ]
