# Generated by Django 3.1 on 2022-02-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='reciepient',
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
