# Generated by Django 3.1 on 2022-02-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directs', '0002_auto_20220212_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
