# Generated by Django 3.1 on 2022-02-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20220208_1234'),
        ('authy', '0002_auto_20220208_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favourite',
            field=models.ManyToManyField(blank=True, to='post.Post'),
        ),
    ]
